-- NOEPRAX isolated runtime schema. Apply through a writable Supabase migration connection.
create schema if not exists noeprax;
grant usage on schema noeprax to service_role;

create table if not exists noeprax.organizations(id uuid primary key default gen_random_uuid(),name text not null,market text not null default 'global',locale text not null default 'en',created_at timestamptz not null default now());
create table if not exists noeprax.memberships(organization_id uuid not null references noeprax.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'member' check(role in('owner','admin','member','viewer')),created_at timestamptz not null default now(),primary key(organization_id,user_id));
create table if not exists noeprax.subscriptions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references noeprax.organizations(id) on delete cascade,plan_key text not null,status text not null default 'trialing' check(status in('trialing','active','past_due','paused','cancelled')),paid_entitlement boolean not null default false,monthly_model_budget_eur numeric(12,4) not null default 0,period_start timestamptz,period_end timestamptz,provider_customer_id text,provider_subscription_id text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists noeprax.business_profiles(id uuid primary key default gen_random_uuid(),organization_id uuid not null references noeprax.organizations(id) on delete cascade,industry text,description text,employee_count integer,country text,locale text,workflows jsonb not null default '[]',software_stack jsonb not null default '[]',pains jsonb not null default '[]',objectives jsonb not null default '[]',confidence numeric(5,4),confirmed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists noeprax.model_registry(model_id text primary key,provider text not null,display_name text not null,billing_class text not null check(billing_class in('free','grant_only','paid_low','paid_mid','paid_premium')),input_usd_per_mtok numeric(12,6),cached_input_usd_per_mtok numeric(12,6),output_usd_per_mtok numeric(12,6),supports_reasoning boolean not null default false,supports_tools boolean not null default false,privacy_class text not null default 'provider_policy',enabled boolean not null default true,free_funnel_eligible boolean not null default false,last_verified_at timestamptz,metadata jsonb not null default '{}',updated_at timestamptz not null default now());
create table if not exists noeprax.model_policies(policy_key text primary key,config jsonb not null default '{}',enabled boolean not null default true,updated_at timestamptz not null default now());
create table if not exists noeprax.service_definitions(service_key text primary key,name text not null,vertical text not null default 'generic',version integer not null default 1,llm_policy jsonb not null default '{}',memory_policy jsonb not null default '{}',tool_policy jsonb not null default '{}',workflow jsonb not null default '{}',autonomy_policy jsonb not null default '{}',evaluation_policy jsonb not null default '{}',billing_policy jsonb not null default '{}',status text not null default 'draft' check(status in('draft','active','paused','retired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists noeprax.agent_definitions(agent_key text primary key,service_key text references noeprax.service_definitions(service_key) on delete set null,name text not null,version integer not null default 1,model_policy_key text references noeprax.model_policies(policy_key),memory_scope text not null default 'organization',allowed_tools jsonb not null default '[]',autonomy_level smallint not null default 1 check(autonomy_level between 0 and 5),max_cost_eur_per_run numeric(12,6) not null default 0,prompt_config jsonb not null default '{}',enabled boolean not null default true,updated_at timestamptz not null default now());
create table if not exists noeprax.tool_registry(tool_key text primary key,name text not null,category text,capabilities jsonb not null default '[]',auth_type text,risk_class text not null default 'low',enabled boolean not null default true,last_verified_at timestamptz,metadata jsonb not null default '{}',updated_at timestamptz not null default now());
create table if not exists noeprax.agent_runs(id uuid primary key default gen_random_uuid(),organization_id uuid references noeprax.organizations(id) on delete cascade,agent_key text references noeprax.agent_definitions(agent_key),entitlement text not null check(entitlement in('free','paid')),model_id text references noeprax.model_registry(model_id),status text not null default 'running' check(status in('queued','running','completed','failed','blocked','cancelled')),input_tokens bigint not null default 0,cached_input_tokens bigint not null default 0,output_tokens bigint not null default 0,estimated_cost_eur numeric(14,8) not null default 0,complexity smallint not null default 1 check(complexity between 1 and 5),sensitive boolean not null default false,correlation_id uuid not null default gen_random_uuid(),result_summary jsonb not null default '{}',error jsonb,started_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists noeprax.memory_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references noeprax.organizations(id) on delete cascade,scope text not null default 'business',subject_key text,content jsonb not null,source text,confidence numeric(5,4),sensitivity text not null default 'normal' check(sensitivity in('public','normal','confidential','sensitive')),expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists noeprax.free_sessions(id uuid primary key default gen_random_uuid(),anonymous_id text,locale text not null default 'en',industry text,calculator_runs integer not null default 0,advisor_runs integer not null default 0,paid_token_cost_eur numeric(14,8) not null default 0 check(paid_token_cost_eur=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists noeprax.incidents(id uuid primary key default gen_random_uuid(),organization_id uuid references noeprax.organizations(id) on delete cascade,severity text not null check(severity in('SEV0','SEV1','SEV2','SEV3','SEV4')),source text not null,status text not null default 'open' check(status in('open','investigating','mitigated','resolved')),title text not null,detail jsonb not null default '{}',created_at timestamptz not null default now(),resolved_at timestamptz);
create table if not exists noeprax.audit_events(id bigint generated always as identity primary key,organization_id uuid references noeprax.organizations(id) on delete set null,actor_type text not null,actor_id text,event_type text not null,target_type text,target_id text,detail jsonb not null default '{}',created_at timestamptz not null default now());

create index if not exists noeprax_agent_runs_org_started_idx on noeprax.agent_runs(organization_id,started_at desc);create index if not exists noeprax_memory_org_scope_idx on noeprax.memory_items(organization_id,scope);create index if not exists noeprax_incidents_status_idx on noeprax.incidents(status,severity,created_at desc);create index if not exists noeprax_audit_org_created_idx on noeprax.audit_events(organization_id,created_at desc);

do $$ declare t text;begin foreach t in array array['organizations','memberships','subscriptions','business_profiles','model_registry','model_policies','service_definitions','agent_definitions','tool_registry','agent_runs','memory_items','free_sessions','incidents','audit_events'] loop execute format('alter table noeprax.%I enable row level security',t);end loop;end $$;
grant select,insert,update,delete on all tables in schema noeprax to service_role;grant usage,select on all sequences in schema noeprax to service_role;
create or replace function noeprax.model_allowed_for_entitlement(p_entitlement text,p_billing_class text)returns boolean language sql immutable as $$select case when p_entitlement='free' then p_billing_class in('free','grant_only') when p_entitlement='paid' then p_billing_class in('free','grant_only','paid_low','paid_mid','paid_premium') else false end$$;grant execute on function noeprax.model_allowed_for_entitlement(text,text) to service_role;

insert into noeprax.model_registry(model_id,provider,display_name,billing_class,input_usd_per_mtok,cached_input_usd_per_mtok,output_usd_per_mtok,supports_reasoning,supports_tools,privacy_class,free_funnel_eligible,last_verified_at,metadata) values
('deterministic','noeprax','NOEPRAX Deterministic Engine','free',0,0,0,false,true,'local',true,'2026-09-10','{"purpose":"calculators,filters,scoring"}'),('openrouter/free','openrouter','OpenRouter Free Router','free',0,0,0,true,true,'provider-dependent',true,'2026-09-10','{"availability":"dynamic"}'),('gemini-3.5-flash-free','google','Gemini 3.5 Flash Free Tier','free',0,0,0,true,true,'public-only',true,'2026-09-10','{"used_to_improve_products":true}'),('deepseek-v4-flash','deepseek','DeepSeek V4 Flash','paid_low',0.22,0.007,0.66,true,true,'provider-policy',false,'2026-09-10','{"pricing":"off_peak_reference","peak_multiplier":2}'),('gpt-5.6-luna','openai','GPT-5.6 Luna','paid_low',0.20,0.02,1.20,true,true,'provider-policy',false,'2026-09-10','{}'),('deepseek-v4-pro','deepseek','DeepSeek V4 Pro','paid_mid',0.66,0.022,1.98,true,true,'provider-policy',false,'2026-09-10','{"pricing":"off_peak_reference","peak_multiplier":2}'),('gpt-5.6-terra','openai','GPT-5.6 Terra','paid_mid',2.00,0.20,12.00,true,true,'provider-policy',false,'2026-09-10','{}'),('gpt-5.6-sol','openai','GPT-5.6 Sol','paid_premium',4.00,0.40,20.00,true,true,'provider-policy',false,'2026-09-10','{"pricing_note":"promotional pricing verified 2026-09-10"}') on conflict(model_id) do update set input_usd_per_mtok=excluded.input_usd_per_mtok,cached_input_usd_per_mtok=excluded.cached_input_usd_per_mtok,output_usd_per_mtok=excluded.output_usd_per_mtok,billing_class=excluded.billing_class,free_funnel_eligible=excluded.free_funnel_eligible,last_verified_at=excluded.last_verified_at,metadata=excluded.metadata,updated_at=now();
insert into noeprax.model_policies(policy_key,config) values('free_public','{"paid_token_budget_eur":0,"allowed_billing_classes":["free","grant_only"],"sensitive_external_inference":false,"fallback":"deterministic"}'),('paid_cost_first','{"default_candidates":["deepseek-v4-flash","gpt-5.6-luna"],"reasoning_candidates":["deepseek-v4-pro","gpt-5.6-terra"],"premium_candidates":["gpt-5.6-sol"],"escalate_on_eval_failure":true}') on conflict(policy_key) do update set config=excluded.config,updated_at=now();
